mic/urls.py
from django.urls import path

from . import views
app_name='mic'

urlpatterns = [
    #/mic
    path('', views.Indexview.as_view(),name='index'),
    # login
    path('reg/', views.Userformview.as_view(),name='register'),
    #/mic/71
    path('<pk>/',views.Detailview.as_view(),name="detail"),
    #mic/album/add
    path('album/add/',views.Albumcreate.as_view(),name="album-add"),
    #/mic/song
     path('/song/', views.songview.as_view(),name='songdetail'),
    #mic/album
    path('/album/', views.albumview.as_view(),name='albumdetail'),

]

web/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mic/', include('mic.urls')),

]

mic/models.py
from django.db import models
from django.urls import reverse

class album(models.Model):
    artist = models.CharField(max_length=250)
    album_tittle = models.CharField(max_length=500)
    album_logo = models.CharField(max_length=2500)
    genre = models.CharField(max_length=250)
    def get_absolute_url(self):
        return reverse('mic:detail',kwargs={'pk':self.pk})


    def __str__(self):
        return self.artist


class song(models.Model):
    album=models.ForeignKey(album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=250)
    song_tittle = models.CharField(max_length=250)
    def __str__(self):
        return self.song_tittle

mic/forms.py
from django.contrib.auth.models import User
from django import forms



class Userform(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields=['username','email','password']

mic/views.py
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .models import album,song
from .forms import Userform


class Indexview(generic.ListView):
    template_name = 'mic/index1.html'

    def get_queryset(self):
        return album.objects.all()


class Detailview(generic.DetailView):
     model = album
     context_object_name = 'al'
     template_name = 'mic/detail1.html'



class Albumcreate(CreateView):
    model = album
    fields = ['artist','album_tittle','genre','album_logo']


class songview(generic.ListView):
    template_name = 'mic/detail2.html'

    def get_queryset(self):
        return song.objects.all()

class albumview(generic.ListView):
    template_name = 'mic/detail3.html'

    def get_queryset(self):
        return album.objects.all()

class Userformview(View):
    form_Class =Userform
    template_name = 'mic/reg.html'
    def get(self,request):
        form =self.form_Class(None)
        return render(request,self.template_name,{'form':form})
    #process form data
    def post(self,request):
        form = self.form_Class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)
            #cleaned(normailzed) data
            username = form.cleaned_data['username']
            password= form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # returns user objects if credentials are correct
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('mic:index')

        return render(request, self.template_name, {'form': form})

mic/templates/mic/album_form.html
{% extends 'mic/base1.html' %}
{% block tittle %}Album details{% endblock %}
{% block albums_active %}active{% endblock%}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> create a new album</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'mic/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mic/templates/mic/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %}vipper{% endblock %}</title>
    {% load static %}
 <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
 <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
 <link href='{% static "mic/style.css" %}' rel='stylesheet' type='text/css'  >
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js" ></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="{% url 'mic:index' %}">Vipper</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'mic:albumdetail' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'mic:songdetail' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left " role="search" method="get" action="#">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="">

            </div>
             <button type="submit" class="btn btn-default">Search</button>
         </form>
           <ul class="nav navbar-nav navbar-right">
               <li class="">
                    <a href=" {% url 'mic:album-add' %}">
                         <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
               <li class="">
                    <a href="{% url 'mic:register' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        LogIn
                    </a>
                </li>

           </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

mic/templates/mic/detail1.html
{% extends 'mic/base1.html' %}
{% block tittle %}Album details{% endblock %}
{% block body %}

 <img src="{{al.album_logo}}">
<h1> {{al.album_tittle}}</h1>

 <h3>{{al.artist}}</h3>
 <ul>
    {% for song in al.song_set.all %}
        <li>{{song.song_tittle}} </li>
    {% endfor %}
 </ul>
{% endblock %}

mic/templates/mic/detail2.html
{% extends 'mic/base1.html' %}

{% block body %}
{% if object_list %}
    <h2>These are all songs:</h2>
 <ul>
    {% for all in object_list %}
       <h3>{{all.song_tittle}}</h3>
    {% endfor %}
 </ul>
{% else %}
    <h3> You dont have any song </h3>
{% endif %}
{% endblock %}

mic/templates/mic/detail3.html
{% extends 'mic/base1.html' %}

{% block body %}
{% if object_list %}
    <h2>These are all albums:</h2>
 <ul>
    {% for all in object_list %}
       <h3>{{all.album_tittle}}</h3>
    {% endfor %}
 </ul>
{% else %}
    <h3> You dont have any album </h3>
{% endif %}
{% endblock %}

mic/templates/mic/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>

    </div>
{% endfor %}

mic/templates/mic/index1.html
<!-- loads the path to static file -->
{% extends 'mic/base1.html' %}

{% block body %}
{% if object_list %}
    <h2>These are all albums:</h2>
 <ul>
    {% for all in object_list %}
    <li><a href="{% url 'mic:detail' all.id %}">{{all.album_tittle}}</a></li>
    {% endfor %}
 </ul>
{% else %}
    <h3> You dont have any albums </h3>
{% endif %}
{% endblock %}

mic/templates/mic/reg.html
{% extends 'mic/base1.html' %}
{% block tittle %}Register{% endblock %}
{% block albums_active %}active{% endblock%}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3> create a new account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'mic/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}